### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by elssm** [seek-ret/ebpf-training#11]
hi，when i in docker exec go run main.go ./sourcecode.c，the error is：
root@ubuntu:/src/workshop1/capture-traffic# go run main.go ./sourcecode.c
go: downloading github.com/iovisor/gobpf v0.2.0
go: downloading golang.org/x/sys v0.0.0-20220227234510-4e6760a101f9
github.com/iovisor/gobpf/bcc
/go/pkg/mod/github.com/iovisor/gobpf@v0.2.0/bcc/module.go:230:28: not enough arguments in call to _C2func_bcc_func_load
	have (unsafe.Pointer, _Ctype_int, *_Ctype_char, *_Ctype_struct_bpf_insn, _Ctype_int, *_Ctype_char, _Ctype_uint, _Ctype_int, *_Ctype_char, _Ctype_uint, nil)
	want (unsafe.Pointer, _Ctype_int, *_Ctype_char, *_Ctype_struct_bpf_insn, _Ctype_int, *_Ctype_char, _Ctype_uint, _Ctype_int, *_Ctype_char, _Ctype_uint, *_Ctype_char, _Ctype_int)
how can i solve ？thanks！

**Comment by guyarb** [comment]
hey @elssm can you share the full command line that you used?

**Comment by elssm** [comment]
ok this is the commond in docker enviroment.
root@ubuntu:/src/workshop1/capture-traffic# go run main.go ./sourcecode.c
package command-line-arguments
	main.go:23:2: use of internal package github.com/seek-ret/ebpf-training/workshop1/internal/bpfwrapper not allowed
package command-line-arguments
	main.go:24:2: use of internal package github.com/seek-ret/ebpf-training/workshop1/internal/connections not allowed
package command-line-arguments
	main.go:25:2: use of internal package github.com/seek-ret/ebpf-training/workshop1/internal/settings not allowed

**Comment by guyarb** [comment]
i meant the command line of the docker
I want to try and reproduce it locally, how did you run the docker?

**Comment by elssm** [comment]
My process is as follows：
first i use docker build -t to make image
then i run setup_docker.sh enter docker enviroment.
finally i run go run main.go ./sourcecode.c
i use docker pull the error is
-> % docker pull gcr.io/seekret/ebpf-training-setup:latest
Error response from daemon: Head "https://gcr.io/v2/seekret/ebpf-training-setup/manifests/latest": denied: Project seekret has been deleted.
So I made my own image
