### ISSUE TITLE
How can I capture all incoming and outgoing HTTP traffic?

### ISSUE THREAD

**Issue by MrWong-code** [seek-ret/ebpf-training#14]

**Comment by guyarb** [comment]
Hey, there are bunch of methods doing so (tracepoints on syscall, kprobes on kernel functions, socket filter and TC)
regardless, there is an example in that specific repo

**Comment by MrWong-code** [comment]
can you give me a link? Thanks

**Comment by guyarb** [comment]
https://github.com/DataDog/ebpf-training/blob/main/workshop1/README.md

**Comment by MrWong-code** [comment]
I apologize for not explaining my intention clearly. I would like to capture network traffic generated by a web browser when it accesses other servers. This includes both incoming and outgoing traffic.

**Comment by guyarb** [comment]
If the traffic is plaintext, then the linked example should work for you
if the traffic is encrypted (tls/ssl) then you'll need to develop your own [implementation](https://github.com/DataDog/ebpf-training/blob/main/workshop5/README.md) which dependent on the application (programming language / shared libraries).
note - the eBPF solution must be running on the host that runs the web browser / target servers
