### ISSUE TITLE
a question about running ebpf on openwrt

### ISSUE THREAD

**Issue by menmazqj** [seek-ret/ebpf-training#9]
Hi,

It is really a good repo for new man. I read the README in this repo, but I found the tutorials does not fit any Linux, openwrt for example. I tried the steps described , but I found it really tough to run eBPF on openwrt. Do you have any thoughts? :(

Best regards

**Comment by guyarb** [comment]
Hey

Have you tried installing BCC from its source code on openwrt?

**Comment by menmazqj** [comment]
> 

Hi,

I failed to try BCC on openwrt, because openwrt master branch just supported eBPF attaching to events, which is the basic of BCC. However, there are other problems with openwrt master branch, that makes me unable to run the system. That means if I want to try BCC, I would get the newest openwrt system working at first. That is really a tough journey.

Best regards

**Comment by menmazqj** [comment]
If I find some way to run eBPF on openwrt, I would open a pull request to this repo. I think many guys need that.
